/**
 * Initial package catalog. Loaded once on first server start into
 * db/packages.json; after that the admin panel is the source of truth.
 *
 * Fields:
 *  - category   → 'Domestic' or 'International' (drives mega-menu grouping)
 *  - region     → logical region within category (e.g. 'South India', 'Europe')
 *  - basePrice  → per-person starting price in INR (used by quotation engine)
 */
export const SEED_PACKAGES = [
    {
        slug: 'maharashtra-explorer',
        title: 'Maharashtra Explorer',
        category: 'Domestic',
        region: 'West India',
        country: 'India',
        city: 'Mumbai · Pune · Nashik',
        days: 7, nights: 6,
        rating: 4.9, reviews: 310,
        basePrice: 28500,
        tags: ['Heritage', 'Culture', 'City'],
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&q=80',
        highlights: [
            'Gateway of India & Marine Drive in Mumbai',
            'Shaniwar Wada & Aga Khan Palace in Pune',
            'Trimbakeshwar Temple & Sula Vineyards in Nashik',
            'Elephanta Caves & Siddhivinayak Temple',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Mumbai',       c: 'Arrive in Mumbai, check-in, evening walk at Marine Drive & Juhu Beach.' },
            { d: 'Day 2', t: 'Mumbai Sightseeing',     c: 'Gateway of India, Elephanta Caves, Film City Mumbai, Haji Ali Dargah.' },
            { d: 'Day 3', t: 'Mumbai to Pune',         c: 'Siddhivinayak Temple, travel to Pune, evening at Shaniwar Wada.' },
            { d: 'Day 4', t: 'Pune Exploration',       c: 'Aga Khan Palace, Sinhagad Fort, Mulshi Lake, Pataleshwar Cave Temple.' },
            { d: 'Day 5', t: 'Pune to Nashik',         c: 'Rajiv Gandhi Zoological Park, Khadakwasla Dam, travel to Nashik.' },
            { d: 'Day 6', t: 'Nashik Heritage',        c: 'Trimbakeshwar Temple, Sula Vineyards, Pandavleni Caves, Godavari River.' },
            { d: 'Day 7', t: 'Departure',              c: 'Anjneri Hills morning visit, Someshwar Waterfalls, departure.' },
        ],
        includes: ['6 nights hotel accommodation', 'Daily breakfast', 'All transfers & sightseeing', 'English-speaking guide'],
        excludes: ['Flights', 'Lunch & dinner', 'Personal expenses', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'delhi-agra-heritage',
        title: 'Delhi & Agra Heritage Trail',
        category: 'Domestic',
        region: 'North India',
        country: 'India',
        city: 'Delhi · Agra',
        days: 5, nights: 4,
        rating: 4.8, reviews: 420,
        basePrice: 19900,
        tags: ['Heritage', 'History', 'UNESCO'],
        image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80',
        highlights: [
            'Taj Mahal — UNESCO World Heritage Site',
            'Red Fort & India Gate in Delhi',
            'Qutub Minar & Lotus Temple',
            'Fatehpur Sikri & Agra Fort',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Delhi',  c: 'Arrive in Delhi, check-in, evening visit to India Gate & Jama Masjid.' },
            { d: 'Day 2', t: 'Delhi City Tour',  c: 'Red Fort, Qutub Minar, Lotus Temple, Akshardham Temple.' },
            { d: 'Day 3', t: 'Delhi to Agra',    c: "Humayun's Tomb, travel to Agra, sunset at Mehtab Bagh with Taj view." },
            { d: 'Day 4', t: 'Agra Exploration', c: 'Taj Mahal sunrise, Agra Fort, Itmad-ud-Daulah Tomb, Fatehpur Sikri.' },
            { d: 'Day 5', t: 'Departure',        c: "Akbar's Tomb, Jama Masjid Agra, departure." },
        ],
        includes: ['4 nights hotel accommodation', 'Daily breakfast', 'AC transfers', 'Monument entry tickets'],
        excludes: ['Flights', 'Lunch & dinner', 'Camera fees at monuments', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'goa-beach-bliss',
        title: 'Goa Beach Bliss',
        category: 'Domestic',
        region: 'West India',
        country: 'India',
        city: 'North Goa · South Goa',
        days: 5, nights: 4,
        rating: 4.9, reviews: 530,
        basePrice: 17500,
        tags: ['Beach', 'Nightlife', 'Adventure'],
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80',
        tourVideo: 'https://videos.pexels.com/video-files/1526909/1526909-hd_1280_720_24fps.mp4',
        highlights: [
            'Baga, Calangute & Anjuna beaches in North Goa',
            'Fort Aguada & Chapora Fort exploration',
            'Colva & Palolem beaches in South Goa',
            'Dudhsagar Waterfalls day trip',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · North Goa', c: 'Arrive in Goa, check-in, evening at Baga Beach & Calangute Beach.' },
            { d: 'Day 2', t: 'North Goa Tour',      c: 'Anjuna Beach, Vagator Beach, Fort Aguada, Chapora Fort, Candolim Beach.' },
            { d: 'Day 3', t: 'South Goa',           c: 'Colva Beach, Benaulim Beach, Palolem Beach, Cabo de Rama Fort.' },
            { d: 'Day 4', t: 'Adventure Day',       c: 'Dudhsagar Waterfalls, Agonda Beach, Butterfly Beach exploration.' },
            { d: 'Day 5', t: 'Departure',           c: 'Morning at leisure, departure.' },
        ],
        includes: ['4 nights beach resort', 'Daily breakfast', 'All transfers & tours', 'Dudhsagar trip included'],
        excludes: ['Flights', 'Water sports', 'Lunch & dinner', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'telangana-discovery',
        title: 'Telangana Cultural Discovery',
        category: 'Domestic',
        region: 'South India',
        country: 'India',
        city: 'Hyderabad · Warangal',
        days: 5, nights: 4,
        rating: 4.8, reviews: 245,
        basePrice: 18400,
        tags: ['Heritage', 'Culture', 'History'],
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&q=80',
        highlights: [
            'Charminar & Golconda Fort in Hyderabad',
            "Ramoji Film City — world's largest film city",
            'Warangal Fort & Thousand Pillar Temple',
            'Hussain Sagar Lake & Birla Mandir',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Hyderabad', c: 'Arrive in Hyderabad, check-in, evening at Hussain Sagar Lake & Birla Mandir.' },
            { d: 'Day 2', t: 'Hyderabad Heritage',  c: 'Charminar, Golconda Fort, Salar Jung Museum, Chowmahalla Palace.' },
            { d: 'Day 3', t: 'Ramoji Film City',    c: 'Full day at Ramoji Film City — guided tour, shows & attractions.' },
            { d: 'Day 4', t: 'Warangal Day Trip',   c: 'Warangal Fort, Ramappa Temple, Thousand Pillar Temple, Bhadrakali Temple.' },
            { d: 'Day 5', t: 'Departure',           c: 'Pakhal Lake visit, departure from Hyderabad.' },
        ],
        includes: ['4 nights hotel accommodation', 'Daily breakfast', 'All transfers & sightseeing', 'Ramoji Film City tickets'],
        excludes: ['Flights', 'Lunch & dinner', 'Personal expenses', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'karnataka-adventure',
        title: 'Karnataka Nature & Heritage',
        category: 'Domestic',
        region: 'South India',
        country: 'India',
        city: 'Coorg · Chikmagalur · Mysore',
        days: 7, nights: 6,
        rating: 4.9, reviews: 380,
        basePrice: 26500,
        tags: ['Hill Station', 'Nature', 'Heritage'],
        image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&q=80',
        highlights: [
            "Abbey Falls & Raja's Seat in Coorg",
            'Mullayanagiri Peak & Hebbe Falls in Chikmagalur',
            'Mysore Palace & Brindavan Gardens',
            'Jog Falls & Gokarna Beach',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Bangalore',    c: 'Arrive in Bangalore, Bangalore Palace, ISKCON Temple, Cubbon Park.' },
            { d: 'Day 2', t: 'Bangalore to Coorg',     c: "Travel to Coorg, Abbey Falls, Raja's Seat sunset, Dubare Elephant Camp." },
            { d: 'Day 3', t: 'Coorg Exploration',      c: 'Chickhole Dam, Nisargadhama, Golden Temple, Iruppu Falls.' },
            { d: 'Day 4', t: 'Coorg to Chikmagalur',   c: 'Travel to Chikmagalur, Mullayanagiri Peak trek, Z Point sunset.' },
            { d: 'Day 5', t: 'Chikmagalur',            c: 'Hebbe Falls, Kalhatti Falls, Coffee Museum, Bhadra Wildlife Sanctuary.' },
            { d: 'Day 6', t: 'Chikmagalur to Mysore',  c: 'Travel to Mysore, Mysore Palace, Chamundi Hills, Brindavan Gardens.' },
            { d: 'Day 7', t: 'Departure',              c: "St. Philomena's Church, Mysore Zoo, departure from Mysore." },
        ],
        includes: ['6 nights hotel/resort', 'Daily breakfast', 'All transfers & sightseeing', 'English-speaking guide'],
        excludes: ['Flights', 'Lunch & dinner', 'Activity charges', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'tamil-nadu-temples-hills',
        title: 'Tamil Nadu Temples & Hills',
        category: 'Domestic',
        region: 'South India',
        country: 'India',
        city: 'Ooty · Kodaikanal · Pondicherry',
        days: 8, nights: 7,
        rating: 4.8, reviews: 350,
        basePrice: 31500,
        tags: ['Hill Station', 'Temple', 'Beach'],
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&q=80',
        highlights: [
            'Doddabetta Peak & Botanical Garden in Ooty',
            'Pillar Rocks & Kodaikanal Lake',
            'Rock Beach & Auroville in Pondicherry',
            'Chettinad Palace heritage in Karaikudi',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Ooty',          c: 'Arrive in Ooty, Botanical Garden, Ooty Lake boating.' },
            { d: 'Day 2', t: 'Ooty Sightseeing',        c: 'Doddabetta Peak, Pykara Lake, Tea Factory visit, Ooty Market.' },
            { d: 'Day 3', t: 'Ooty to Kodaikanal',      c: 'Travel to Kodaikanal, Pillar Rocks, Pine Forest walk.' },
            { d: 'Day 4', t: 'Kodaikanal',              c: "Kodaikanal Lake, Guna Caves, Silver Cascade Falls, Coaker's Walk, Green Valley View." },
            { d: 'Day 5', t: 'Kodaikanal to Pollachi',  c: 'Travel via Pollachi, Aliyar Dam, Topslip, Valparai, Monkey Falls.' },
            { d: 'Day 6', t: 'Pondicherry',             c: 'Travel to Pondicherry, Rock Beach, Auroville, White Town, Promenade Beach.' },
            { d: 'Day 7', t: 'Pondicherry & Karaikudi', c: 'French War Memorial, Chunnambar Boat House, travel to Karaikudi, Chettinad Palace.' },
            { d: 'Day 8', t: 'Departure',               c: 'Athangudi Palace, Athangudi Tiles Factory, departure.' },
        ],
        includes: ['7 nights hotel accommodation', 'Daily breakfast', 'All transfers & sightseeing', 'English-speaking guide'],
        excludes: ['Flights', 'Lunch & dinner', 'Boating charges', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'kerala-gods-own-country',
        title: "Kerala — God's Own Country",
        category: 'Domestic',
        region: 'South India',
        country: 'India',
        city: 'Munnar · Alleppey · Kochi · Wayanad',
        days: 8, nights: 7,
        rating: 5.0, reviews: 480,
        basePrice: 34500,
        tags: ['Backwaters', 'Hill Station', 'Nature'],
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80',
        tourVideo: 'https://videos.pexels.com/video-files/1851190/1851190-hd_1280_720_25fps.mp4',
        highlights: [
            'Houseboat cruise through Alleppey backwaters',
            'Munnar tea gardens & sunrise viewpoint',
            'Fort Kochi heritage walk & Chinese Fishing Nets',
            'Wayanad wildlife & Edakkal Caves',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Kochi',     c: 'Arrive in Kochi, Fort Kochi, Marine Drive, Chinese Fishing Nets, Jew Town.' },
            { d: 'Day 2', t: 'Kochi to Munnar',     c: 'Travel to Munnar, Cherai Beach enroute, evening at Rose Garden.' },
            { d: 'Day 3', t: 'Munnar Sightseeing',  c: 'Sunrise View Point, Mattupetty Dam, Echo Point, Tea Museum, Elephant Camp.' },
            { d: 'Day 4', t: 'Munnar to Vagamon',   c: 'Travel to Vagamon, Vagamon Meadows, Pine Forest, Vagamon Lake.' },
            { d: 'Day 5', t: 'Vagamon to Alleppey', c: 'Paragliding Point, travel to Alleppey, Alleppey Beach, Vembanad Lake.' },
            { d: 'Day 6', t: 'Alleppey Houseboat',  c: 'Full-day houseboat cruise through Alleppey Backwaters, Marari Beach.' },
            { d: 'Day 7', t: 'Alleppey to Wayanad', c: 'Travel to Wayanad, Banasura Sagar Dam, Edakkal Caves, Soochipara Waterfalls.' },
            { d: 'Day 8', t: 'Departure',           c: 'Meenmutty Waterfalls, Pookode Lake, Chembra Peak view, departure.' },
        ],
        includes: ['7 nights hotel/houseboat', 'Daily breakfast', 'Houseboat with meals', 'All transfers & sightseeing'],
        excludes: ['Flights', 'Lunch & dinner (except houseboat)', 'Activity charges', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'dubai-desert-luxury',
        title: 'Dubai Desert & Skyline Luxury',
        category: 'International',
        region: 'Middle East',
        country: 'UAE',
        city: 'Dubai · Abu Dhabi',
        days: 6, nights: 5,
        rating: 4.9, reviews: 290,
        basePrice: 78900,
        tags: ['Luxury', 'Desert', 'City'],
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
        tourVideo: 'https://videos.pexels.com/video-files/1526909/1526909-hd_1280_720_24fps.mp4',
        highlights: [
            'Burj Khalifa At the Top (124th Floor)',
            'Desert Safari with BBQ dinner + belly dance',
            'Sheikh Zayed Grand Mosque, Abu Dhabi',
            'Dubai Marina Yacht Cruise',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Dubai',       c: 'Arrive DXB, check-in, evening stroll at Dubai Marina & JBR walk.' },
            { d: 'Day 2', t: 'Dubai City Tour',       c: 'Burj Khalifa, Dubai Mall fountains, Museum of the Future, Palm Jumeirah.' },
            { d: 'Day 3', t: 'Desert Safari',         c: 'Dune bashing, camel ride, Bedouin camp BBQ, Tanoura show.' },
            { d: 'Day 4', t: 'Abu Dhabi Day',         c: 'Sheikh Zayed Mosque, Louvre Abu Dhabi, Ferrari World, Corniche drive.' },
            { d: 'Day 5', t: 'Theme Park + Marina',   c: 'Atlantis Aquaventure or IMG Worlds, evening yacht cruise.' },
            { d: 'Day 6', t: 'Departure',             c: 'Gold Souk shopping, departure.' },
        ],
        includes: ['5 nights 4★/5★ hotel', 'Daily breakfast', 'All tours with guide', 'Burj Khalifa + desert safari tickets'],
        excludes: ['International flights', 'UAE visa (we can arrange)', 'Lunch & dinner (except safari)', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'singapore-malaysia-explorer',
        title: 'Singapore & Malaysia Explorer',
        category: 'International',
        region: 'South-East Asia',
        country: 'Singapore & Malaysia',
        city: 'Singapore · Kuala Lumpur · Genting',
        days: 7, nights: 6,
        rating: 4.8, reviews: 210,
        basePrice: 89500,
        tags: ['Family', 'Theme Park', 'City'],
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=80',
        highlights: [
            'Universal Studios Singapore',
            'Gardens by the Bay & Marina Bay Sands SkyPark',
            'Petronas Twin Towers, Kuala Lumpur',
            'Genting Highlands cable car + theme park',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Singapore',   c: 'Arrive SIN, Marina Bay light show, Merlion park.' },
            { d: 'Day 2', t: 'Universal Studios',     c: 'Full-day Universal Studios Sentosa, cable car, Siloso Beach.' },
            { d: 'Day 3', t: 'Gardens + Night Safari',c: 'Gardens by the Bay, Cloud Forest, Singapore Night Safari.' },
            { d: 'Day 4', t: 'Singapore to KL',       c: 'Flight to Kuala Lumpur, Petronas Towers, Bukit Bintang.' },
            { d: 'Day 5', t: 'Genting Highlands',     c: 'Day trip to Genting — Awana SkyWay, theme park, casino resort.' },
            { d: 'Day 6', t: 'Batu Caves + Shopping', c: 'Batu Caves, KL Tower, Central Market shopping.' },
            { d: 'Day 7', t: 'Departure',             c: 'Breakfast, airport transfer, depart.' },
        ],
        includes: ['6 nights 4★ hotel', 'Daily breakfast', 'Inter-city flight SIN–KL', 'Universal Studios + Genting tickets'],
        excludes: ['International flights', 'Visas', 'Lunch & dinner', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'bali-honeymoon-escape',
        title: 'Bali Honeymoon Escape',
        category: 'International',
        region: 'South-East Asia',
        country: 'Indonesia',
        city: 'Ubud · Seminyak · Nusa Penida',
        days: 6, nights: 5,
        rating: 5.0, reviews: 185,
        basePrice: 64500,
        tags: ['Honeymoon', 'Beach', 'Nature'],
        image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80',
        tourVideo: 'https://videos.pexels.com/video-files/1851190/1851190-hd_1280_720_25fps.mp4',
        highlights: [
            'Private pool villa in Ubud jungle',
            'Nusa Penida Kelingking Beach day trip',
            'Tanah Lot sunset + Uluwatu Kecak fire dance',
            'Couple spa + floating breakfast',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Seminyak',    c: 'Arrive DPS, check-in beachside resort, sunset at Double Six.' },
            { d: 'Day 2', t: 'Nusa Penida',           c: 'Speedboat to Nusa Penida, Kelingking, Broken Beach, Angel\'s Billabong.' },
            { d: 'Day 3', t: 'Seminyak to Ubud',     c: 'Tanah Lot temple, Ubud jungle villa check-in, evening Kecak fire dance at Uluwatu.' },
            { d: 'Day 4', t: 'Ubud',                  c: 'Tegallalang rice terraces, Sacred Monkey Forest, couple spa, candlelit dinner.' },
            { d: 'Day 5', t: 'Waterfalls + Leisure',  c: 'Tibumana waterfall, Campuhan ridge walk, free afternoon at villa pool.' },
            { d: 'Day 6', t: 'Departure',             c: 'Floating breakfast, departure transfer.' },
        ],
        includes: ['5 nights (3N beach + 2N jungle villa)', 'Daily breakfast + 1 floating breakfast', 'All transfers', 'Nusa Penida speedboat'],
        excludes: ['International flights', 'VOA fee', 'Lunch & dinner (except candlelit)', 'Travel insurance'],
        published: true,
    },
    {
        slug: 'europe-4-country-grand-tour',
        title: 'Europe 4-Country Grand Tour',
        category: 'International',
        region: 'Europe',
        country: 'France · Switzerland · Italy · Netherlands',
        city: 'Paris · Lucerne · Rome · Amsterdam',
        days: 11, nights: 10,
        rating: 4.9, reviews: 140,
        basePrice: 219000,
        tags: ['Europe', 'Luxury', 'Heritage'],
        image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80',
        highlights: [
            'Eiffel Tower summit + Seine cruise',
            'Mt. Titlis snow experience',
            'Colosseum + Vatican skip-the-line',
            'Amsterdam canal cruise + Keukenhof (seasonal)',
        ],
        itinerary: [
            { d: 'Day 1', t: 'Arrival · Paris',       c: 'Arrive CDG, Seine dinner cruise.' },
            { d: 'Day 2', t: 'Paris',                 c: 'Louvre, Eiffel summit, Champs-Élysées.' },
            { d: 'Day 3', t: 'Paris to Lucerne',      c: 'High-speed TGV to Switzerland, Lucerne old town.' },
            { d: 'Day 4', t: 'Mt. Titlis',            c: 'Rotair cable car, glacier walk, Titlis Cliff Walk.' },
            { d: 'Day 5', t: 'Lucerne to Rome',       c: 'Flight to Rome, Trevi Fountain, Spanish Steps.' },
            { d: 'Day 6', t: 'Rome',                  c: 'Colosseum, Roman Forum, Vatican Museums, Sistine Chapel.' },
            { d: 'Day 7', t: 'Rome + Florence DT',    c: 'Day trip to Florence — Duomo, Ponte Vecchio.' },
            { d: 'Day 8', t: 'Rome to Amsterdam',     c: 'Flight to AMS, evening canal cruise.' },
            { d: 'Day 9', t: 'Amsterdam',             c: 'Van Gogh Museum, Anne Frank House, Zaanse Schans windmills.' },
            { d: 'Day 10', t: 'Volendam + Leisure',   c: 'Volendam fishing village, cheese farm, leisure evening.' },
            { d: 'Day 11', t: 'Departure',            c: 'Airport transfer, depart.' },
        ],
        includes: ['10 nights 4★ hotels', 'Daily breakfast + 3 dinners', 'All inter-city flights/trains', 'Paris + Rome + Amsterdam attractions'],
        excludes: ['International flights', 'Schengen visa (we assist)', 'Most meals', 'Travel insurance'],
        published: true,
    },
];
