/**
 * Seed for the standalone Destinations + Popular Holidays catalogue.
 *
 * IMPORTANT — these are NOT the same as the bookable `packages` collection.
 * The packages collection has the full quotation + UPI booking flow. This
 * collection only powers a lightweight "browse → enquire" funnel.
 *
 * priceFrom is intentionally 0 in the seed so the UI hides the price chip
 * by default. Admin can set a number later to make it appear.
 *
 * Each entry includes a `places` array — the tourist spots inside that
 * destination (e.g. Dubai → Burj Khalifa, Dubai Mall …) — so the detail
 * page can show a rich list of attractions and let visitors enquire about
 * any of them.
 */

const px = (id, w = 1600) =>
    `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

// Curated, reusable image library — each place picks the most fitting one
const IMG = {
    skyline:   px(2363807),
    burj:      px(162031),
    marina:    px(3787839),
    mall:      px(2034335),
    desert:    px(2649348),
    palm:      px(823696),
    yacht:     px(906982),
    waterfall: px(414171),
    beach:     px(1032650),
    island:    px(1268855),
    overwater: px(1287460),
    snorkel:   px(3155666),
    forest:    px(2474690),
    riceTerrace: px(2100941),
    temple:    px(2387873),
    pagoda:    px(2070033),
    fort:      px(2376404),
    palace:    px(789750),
    market:    px(1449773),
    streetfood: px(1410235),
    food:      px(1410235),
    mountain:  px(1271619),
    snow:      px(1666021),
    glacier:   px(417054),
    matterhorn: px(346529),
    lake:      px(670261),
    eiffel:    px(338515),
    louvre:    px(699466),
    versailles: px(1530259),
    seine:     px(2363807),
    cappadocia: px(2563681),
    balloon:   px(3214944),
    pamukkale: px(1797161),
    bigben:    px(460672),
    london:    px(672532),
    london2:   px(427679),
    backwaters: px(3881104),
    teaEstate: px(3935702),
    spice:     px(1108099),
    goa:       px(2049422),
    rajPalace: px(2376404),
    camel:     px(2649348),
    folkDance: px(2387873),
    shikara:   px(1666021),
    tulip:     px(1108099),
    mughal:    px(2376404),
    snowSlope: px(346529),
    toyTrain:  px(670261),
    rohtang:   px(1271619),
    radhanagar: px(1032650),
    scuba:     px(3155666),
    cellular:  px(2376404),
    rhino:     px(259411),
    rootBridge: px(414171),
    shillong:  px(2031706),
    tanjore:   px(2387873),
    madurai:   px(2376404),
    rameswaram: px(2474690),
    chettinad: px(1410235),
    hawaMahal: px(789750),
    amerFort:  px(2376404),
    udaipur:   px(670261),
    jaisalmer: px(2649348),
    grandPalace: px(2387873),
    phiPhi:    px(2506923),
    floatMarket: px(1450353),
    bigBuddha: px(2403016),
    universal: px(326701),
    gardens:   px(326709),
    sentosa:   px(2031706),
    hawker:    px(745243),
    halong:    px(1486577),
    hoiAn:     px(1271619),
    cuChi:     px(2476154),
    mekong:    px(3593922),
    sigiriya:  px(2403209),
    galle:     px(3414116),
    kandy:     px(3581368),
    ella:      px(2474690),
    catamaran: px(995765),
    chamarel:  px(1450363),
    casela:    px(259411),
    blackRiver: px(414171),
};

const D = (entry) => ({
    priceFrom: 0,         // hidden by default — admin sets a value to show
    rating: undefined,    // hidden when missing
    reviews: undefined,
    ...entry,
});

export const SEED_DESTINATIONS = [
    /* ============================================================
     * TOP INTERNATIONAL DESTINATIONS (12)
     * ============================================================ */
    D({
        slug: 'dubai', kind: 'top', title: 'Dubai',
        location: 'Burj-lit skyline & golden dunes',
        country: 'United Arab Emirates',
        days: 5, nights: 4,
        image: IMG.burj,
        gallery: [IMG.marina, IMG.palm, IMG.desert, IMG.mall],
        bestTime: 'Nov - Mar',
        tags: ['Luxury', 'Family', 'City'],
        intro: 'Glass towers, gold-trimmed sunsets, and yacht brunches against the Burj. Dubai serves up scale, indulgence and desert silence within the same long weekend.',
        highlights: [
            'Burj Khalifa observation deck (124th floor)',
            'Desert safari with belly-dance dinner',
            'Dhow cruise on Dubai Creek',
            'Palm Jumeirah & Atlantis Aquaventure',
            'Gold Souk + Dubai Mall shopping',
        ],
        places: [
            { slug: 'burj-khalifa',    name: 'Burj Khalifa',          category: 'Landmark', image: IMG.burj,      desc: 'World\'s tallest tower. Sunset on the 124th-floor observation deck is unforgettable.' },
            { slug: 'dubai-mall',      name: 'The Dubai Mall',        category: 'Shopping', image: IMG.mall,      desc: '1,200 stores, an aquarium and the dancing fountain — bigger than any mall has the right to be.' },
            { slug: 'palm-jumeirah',   name: 'Palm Jumeirah',         category: 'Landmark', image: IMG.palm,      desc: 'Man-made palm-shaped island. Atlantis, beach clubs, and sky views from The View at the Palm.' },
            { slug: 'desert-safari',   name: 'Desert Safari',         category: 'Adventure', image: IMG.desert,   desc: 'Dune-bashing 4×4 ride into the dunes, camel rides, henna and an Arabian buffet under the stars.' },
            { slug: 'dubai-marina',    name: 'Dubai Marina',          category: 'Sightseeing', image: IMG.marina, desc: 'Skyscraper-lined waterfront — yacht cruises, Marina Walk dining, JBR Beach.' },
            { slug: 'gold-souk',       name: 'Gold & Spice Souk',     category: 'Shopping', image: IMG.market,    desc: 'Old Dubai\'s glittering alleys — jewellery, saffron, frankincense and local life.' },
            { slug: 'atlantis-aquaventure', name: 'Atlantis Aquaventure', category: 'Adventure', image: IMG.beach, desc: 'Mega water park with shark-tank slides and dolphin encounters. Family favourite.' },
        ],
    }),

    D({
        slug: 'singapore', kind: 'top', title: 'Singapore',
        location: 'Garden city of the future',
        country: 'Singapore',
        days: 5, nights: 4,
        image: IMG.gardens,
        gallery: [IMG.skyline, IMG.universal, IMG.sentosa, IMG.hawker],
        bestTime: 'Feb - Apr',
        tags: ['Family', 'City', 'Honeymoon'],
        intro: 'Squeaky-clean, perfectly engineered and absurdly green — Singapore is where futuristic skylines and old-Malay kampong charm hold hands. Easy first stamp for families.',
        highlights: [
            'Gardens by the Bay & Cloud Forest dome',
            'Universal Studios Sentosa',
            'Marina Bay Sands Skypark',
            'Sentosa Beach + S.E.A. Aquarium',
            'Hawker-stall food crawl on Maxwell Road',
        ],
        places: [
            { slug: 'gardens-by-the-bay', name: 'Gardens by the Bay', category: 'Nature', image: IMG.gardens, desc: 'Supertree groves and the Cloud Forest dome — a botanical wonderland after dark.' },
            { slug: 'marina-bay-sands',   name: 'Marina Bay Sands',   category: 'Landmark', image: IMG.skyline, desc: 'Iconic three-tower hotel. Skypark infinity pool, ArtScience Museum below.' },
            { slug: 'universal-studios',  name: 'Universal Studios',  category: 'Adventure', image: IMG.universal, desc: 'Sentosa\'s headline theme park — Transformers, Jurassic Park and family rides for every age.' },
            { slug: 'sentosa-island',     name: 'Sentosa Island',     category: 'Beach', image: IMG.sentosa, desc: 'Resort island with beaches, S.E.A. Aquarium, cable cars and a luge ride.' },
            { slug: 'hawker-centres',     name: 'Hawker Centres',     category: 'Food', image: IMG.hawker, desc: 'Maxwell, Lau Pa Sat, Old Airport Road — Michelin-rated street food at $5 a plate.' },
            { slug: 'merlion-park',       name: 'Merlion Park',       category: 'Sightseeing', image: IMG.skyline, desc: 'The half-lion, half-fish national mascot, gushing into Marina Bay.' },
        ],
    }),

    D({
        slug: 'thailand', kind: 'top', title: 'Thailand',
        location: 'Bangkok · Pattaya · Phuket',
        country: 'Thailand',
        days: 6, nights: 5,
        image: IMG.phiPhi,
        gallery: [IMG.grandPalace, IMG.bigBuddha, IMG.floatMarket, IMG.beach],
        bestTime: 'Nov - Feb',
        tags: ['Beach', 'Honeymoon', 'Friends'],
        intro: 'Beach-bum Phuket, neon-buzz Bangkok and party-coast Pattaya — Thailand packs three vacations into one. Mango sticky rice for dessert, every day.',
        highlights: [
            'Phi Phi & James Bond island hopping',
            'Tuk-tuk temple trail in Bangkok',
            'Coral Island speedboat from Pattaya',
            'Tiger Park + Big Buddha views',
            'Floating market & street-food tour',
        ],
        places: [
            { slug: 'phi-phi-islands',   name: 'Phi Phi Islands',   category: 'Beach', image: IMG.phiPhi, desc: 'The most photogenic island chain in Asia — Maya Bay\'s emerald cove, day-tour speedboats from Phuket.' },
            { slug: 'grand-palace',      name: 'Grand Palace',      category: 'Heritage', image: IMG.grandPalace, desc: 'Bangkok\'s gold-spired royal complex. Wat Phra Kaew\'s emerald Buddha is right next door.' },
            { slug: 'big-buddha-phuket', name: 'Big Buddha (Phuket)', category: 'Landmark', image: IMG.bigBuddha, desc: '45-metre marble Buddha on a hilltop. Sunset views over Chalong Bay.' },
            { slug: 'floating-market',   name: 'Damnoen Saduak Floating Market', category: 'Food', image: IMG.floatMarket, desc: 'Long-tail boats stacked with mangoes, pad thai and coconut ice cream.' },
            { slug: 'coral-island',      name: 'Coral Island (Pattaya)', category: 'Adventure', image: IMG.beach, desc: 'Speedboat over to Koh Larn for parasailing, banana-boat rides and seafood lunch.' },
            { slug: 'tiger-park',        name: 'Tiger Kingdom',     category: 'Adventure', image: IMG.forest, desc: 'Pose with Bengal tigers in their enclosure. Phuket\'s most-photographed attraction.' },
        ],
    }),

    D({
        slug: 'bali', kind: 'top', title: 'Bali',
        location: 'Ubud rice terraces & Seminyak shores',
        country: 'Indonesia',
        days: 7, nights: 6,
        image: IMG.riceTerrace,
        gallery: [IMG.forest, IMG.temple, IMG.beach, IMG.snorkel],
        bestTime: 'Apr - Oct',
        tags: ['Honeymoon', 'Beach', 'Wellness'],
        intro: 'Slow Bali mornings, jungle-villa breakfasts and Seminyak twilight dinners — the honeymoon island still earns its name. Ten years on, still magical.',
        highlights: [
            'Ubud rice-terrace sunrise + monkey forest',
            'Tanah Lot temple at golden hour',
            'Floating breakfast in a private villa',
            'Nusa Penida island day-trip',
            'Seminyak beach club sunset cocktails',
        ],
        places: [
            { slug: 'tanah-lot',     name: 'Tanah Lot Temple', category: 'Temple', image: IMG.temple, desc: 'Sea-temple on a tide-cut rock. Sunset here is the postcard everyone takes home.' },
            { slug: 'tegalalang',    name: 'Tegalalang Rice Terraces', category: 'Nature', image: IMG.riceTerrace, desc: 'Cascading rice paddies cut into a jungle valley. Best at sunrise, before the day-trippers.' },
            { slug: 'ubud-monkey',   name: 'Ubud Monkey Forest', category: 'Nature', image: IMG.forest, desc: 'Sacred banyan-shrouded sanctuary with hundreds of long-tailed macaques. Hold onto your sunglasses.' },
            { slug: 'nusa-penida',   name: 'Nusa Penida', category: 'Adventure', image: IMG.beach, desc: 'Cliff-edged island day-trip — Kelingking T-Rex viewpoint, Angel\'s Billabong, Crystal Bay snorkel.' },
            { slug: 'seminyak-beach', name: 'Seminyak Beach', category: 'Beach', image: IMG.beach, desc: 'Wide sandy beach, surf-rental shacks and beach clubs (Potato Head, Ku De Ta) for sunset.' },
            { slug: 'uluwatu-temple', name: 'Uluwatu Cliff Temple', category: 'Temple', image: IMG.temple, desc: 'Clifftop temple 70m above the Indian Ocean. The sunset Kecak fire dance is unmissable.' },
        ],
    }),

    D({
        slug: 'maldives', kind: 'top', title: 'Maldives',
        location: 'Overwater villas & turquoise lagoons',
        country: 'Maldives',
        days: 5, nights: 4,
        image: IMG.overwater,
        gallery: [IMG.island, IMG.snorkel, IMG.beach, IMG.catamaran],
        bestTime: 'Nov - Apr',
        tags: ['Luxury', 'Honeymoon', 'Beach'],
        intro: 'You step off a seaplane into a postcard. Endless aquamarine, your own deck over the lagoon, and silence broken only by lapping water.',
        highlights: [
            'Overwater villa with private pool',
            'Snorkelling with reef sharks & turtles',
            'Sandbank picnic on a deserted islet',
            'Sunset dolphin cruise',
            'Underwater spa or restaurant experience',
        ],
        places: [
            { slug: 'overwater-villas',  name: 'Overwater Villas', category: 'Stay', image: IMG.overwater, desc: 'Stilted bungalows with glass floors, private pools and ladders straight into the lagoon.' },
            { slug: 'sandbank-picnic',   name: 'Private Sandbank', category: 'Beach', image: IMG.island, desc: 'Speedboat to a tiny crescent of pure white sand. Champagne picnic, then back at high tide.' },
            { slug: 'manta-snorkel',     name: 'Manta & Reef-Shark Snorkel', category: 'Adventure', image: IMG.snorkel, desc: 'Drift over coral pinnacles with eagle rays, parrotfish and reef sharks gliding below.' },
            { slug: 'dolphin-cruise',    name: 'Sunset Dolphin Cruise', category: 'Adventure', image: IMG.catamaran, desc: 'Catamaran trip at golden hour — pods of spinner dolphins racing the bow wake.' },
            { slug: 'underwater-restaurant', name: 'Underwater Restaurant', category: 'Food', image: IMG.snorkel, desc: 'Dinner 5m below the surface, surrounded by reef life. Hudhuran Fushi & Niyama do this best.' },
        ],
    }),

    D({
        slug: 'vietnam', kind: 'top', title: 'Vietnam',
        location: 'Hanoi · Halong · Hoi An · Ho Chi Minh',
        country: 'Vietnam',
        days: 8, nights: 7,
        image: IMG.halong,
        gallery: [IMG.hoiAn, IMG.cuChi, IMG.mekong, IMG.streetfood],
        bestTime: 'Oct - Apr',
        tags: ['Heritage', 'Adventure', 'Culture'],
        intro: 'Misty limestone islands, lantern-lit Hoi An streets and the buzz of Hanoi mopeds — Vietnam is the most underrated country in South-East Asia.',
        highlights: [
            'Overnight cruise on Halong Bay',
            'Lantern-lit walks in old-town Hoi An',
            'Cu Chi tunnels war-history tour',
            'Mekong Delta long-boat ride',
            'Pho + egg-coffee street tasting',
        ],
        places: [
            { slug: 'halong-bay',       name: 'Halong Bay Cruise', category: 'Nature', image: IMG.halong, desc: '1,600 limestone karsts in jade water — overnight junk-boat cruise with kayaking and tai-chi at dawn.' },
            { slug: 'hoi-an',           name: 'Hoi An Old Town',   category: 'Heritage', image: IMG.hoiAn, desc: 'UNESCO lantern-lit trading town. Tailors, riverside dining and bicycle rides through rice fields.' },
            { slug: 'cu-chi-tunnels',   name: 'Cu Chi Tunnels',    category: 'Heritage', image: IMG.cuChi, desc: 'Vietnam War tunnel network. Crawl through, fire an AK at the range, learn the stories.' },
            { slug: 'mekong-delta',     name: 'Mekong Delta',      category: 'Nature', image: IMG.mekong, desc: 'Long-boat through floating markets, coconut-candy workshops and stilt-house villages.' },
            { slug: 'hanoi-old-quarter', name: 'Hanoi Old Quarter', category: 'Food', image: IMG.streetfood, desc: '36 streets, 36 trades — pho stalls, egg-coffee cafes and chaos in the best possible way.' },
        ],
    }),

    D({
        slug: 'sri-lanka', kind: 'top', title: 'Sri Lanka',
        location: 'Sigiriya · Kandy · Galle',
        country: 'Sri Lanka',
        days: 6, nights: 5,
        image: IMG.sigiriya,
        gallery: [IMG.kandy, IMG.ella, IMG.galle, IMG.beach],
        bestTime: 'Dec - Mar',
        tags: ['Heritage', 'Family', 'Beach'],
        intro: 'A whole subcontinent in one tear-shaped island. Beaches, jungles, ruined cities, hill stations, surf — Sri Lanka punches well above its size.',
        highlights: [
            'Lion Rock fortress climb at Sigiriya',
            'Temple of the Tooth at Kandy',
            'Tea-train ride Kandy → Ella',
            'Galle fort sunset walk',
            'Mirissa whale-watching cruise',
        ],
        places: [
            { slug: 'sigiriya',     name: 'Sigiriya Lion Rock', category: 'Heritage', image: IMG.sigiriya, desc: '5th-century rock fortress with frescoes and lion-paw entrance. The 1,200-step climb pays off in views.' },
            { slug: 'kandy-temple', name: 'Temple of the Tooth (Kandy)', category: 'Temple', image: IMG.kandy, desc: 'Sri Lanka\'s holiest Buddhist site, holding the relic of Buddha\'s tooth. Evening puja is mesmeric.' },
            { slug: 'ella-train',   name: 'Kandy → Ella Train Ride', category: 'Sightseeing', image: IMG.ella, desc: 'Often called the world\'s most beautiful train journey — through tea estates and waterfalls.' },
            { slug: 'galle-fort',   name: 'Galle Fort', category: 'Heritage', image: IMG.galle, desc: '17th-century Dutch ramparts. Sunset on the walls, boutique cafes inside.' },
            { slug: 'mirissa-whales', name: 'Mirissa Whale Watching', category: 'Adventure', image: IMG.catamaran, desc: 'Blue whales (the largest creatures on earth!) and pods of spinner dolphins, Dec-Apr.' },
        ],
    }),

    D({
        slug: 'switzerland', kind: 'top', title: 'Switzerland',
        location: 'Zurich · Lucerne · Interlaken · Zermatt',
        country: 'Switzerland',
        days: 7, nights: 6,
        image: IMG.matterhorn,
        gallery: [IMG.glacier, IMG.lake, IMG.snow, IMG.mountain],
        bestTime: 'May - Sep',
        tags: ['Honeymoon', 'Luxury', 'Mountain'],
        intro: 'Picture-perfect, weirdly punctual, and somehow even prettier in person. Switzerland is the European bucket-list trip everyone deserves once.',
        highlights: [
            'Glacier Express scenic rail',
            'Jungfraujoch — Top of Europe',
            'Matterhorn views from Gornergrat',
            'Mt. Titlis cable-car ride',
            'Lake Lucerne paddle-steamer',
        ],
        places: [
            { slug: 'jungfraujoch',   name: 'Jungfraujoch — Top of Europe', category: 'Mountain', image: IMG.snow, desc: 'Highest railway station in Europe (3,454m). Ice palace, sphinx observatory, eternal snow.' },
            { slug: 'matterhorn',     name: 'Matterhorn Gornergrat', category: 'Mountain', image: IMG.matterhorn, desc: 'Zermatt\'s iconic pyramid peak, viewed from the Gornergrat ridge railway.' },
            { slug: 'mt-titlis',      name: 'Mount Titlis Glacier', category: 'Adventure', image: IMG.glacier, desc: 'Rotating cable-car to a glacier playground — ice cave, cliff walk and snow tubing.' },
            { slug: 'lake-lucerne',   name: 'Lake Lucerne Cruise', category: 'Sightseeing', image: IMG.lake, desc: 'Old-world paddle steamer through Switzerland\'s prettiest lake.' },
            { slug: 'glacier-express', name: 'Glacier Express', category: 'Sightseeing', image: IMG.snow, desc: '8-hour panoramic train through 291 bridges and 91 tunnels — Zermatt to St. Moritz.' },
        ],
    }),

    D({
        slug: 'paris', kind: 'top', title: 'Paris',
        location: 'City of light',
        country: 'France',
        days: 5, nights: 4,
        image: IMG.eiffel,
        gallery: [IMG.louvre, IMG.versailles, IMG.seine, IMG.market],
        bestTime: 'Apr - Jun',
        tags: ['Honeymoon', 'Culture', 'Heritage'],
        intro: 'Cobblestones, croissants, accordion soundtracks. Paris is the cliché that earns every word — wear comfortable shoes and let it work on you.',
        highlights: [
            'Eiffel Tower second-floor entry',
            'Louvre + Mona Lisa skip-the-line',
            'Seine river cruise at twilight',
            'Versailles palace day-trip',
            'Montmartre + Sacré-Cœur walk',
        ],
        places: [
            { slug: 'eiffel-tower',   name: 'Eiffel Tower',     category: 'Landmark', image: IMG.eiffel, desc: 'The tower that needs no introduction. Second-floor for views, first-floor glass walk for thrills.' },
            { slug: 'louvre-museum',  name: 'Louvre Museum',    category: 'Heritage', image: IMG.louvre, desc: 'Mona Lisa, Venus de Milo, the Egyptian wing — the world\'s largest art museum. Half-day minimum.' },
            { slug: 'versailles',     name: 'Palace of Versailles', category: 'Heritage', image: IMG.versailles, desc: 'Louis XIV\'s gilded fantasy. Hall of Mirrors, manicured gardens, royal apartments.' },
            { slug: 'seine-cruise',   name: 'Seine River Cruise', category: 'Sightseeing', image: IMG.seine, desc: 'Glide past Notre-Dame, Pont Alexandre and the Eiffel Tower at twilight on a glass-roof boat.' },
            { slug: 'montmartre',     name: 'Montmartre & Sacré-Cœur', category: 'Sightseeing', image: IMG.market, desc: 'Cobbled hill, white-domed basilica, sketch artists at Place du Tertre and Amélie cafés.' },
        ],
    }),

    D({
        slug: 'turkey', kind: 'top', title: 'Turkey',
        location: 'Istanbul · Cappadocia · Pamukkale',
        country: 'Türkiye',
        days: 8, nights: 7,
        image: IMG.cappadocia,
        gallery: [IMG.balloon, IMG.pamukkale, IMG.market, IMG.skyline],
        bestTime: 'Apr - Oct',
        tags: ['Adventure', 'Heritage', 'Honeymoon'],
        intro: 'Where Asia and Europe meet over baklava. Sunrise hot-air balloons in Cappadocia and rooftop calls to prayer in Istanbul — Turkey is unforgettable.',
        highlights: [
            'Hot-air balloon over Cappadocia',
            'Hagia Sophia + Blue Mosque tour',
            'Pamukkale white-travertine pools',
            'Bosphorus dinner cruise',
            'Grand Bazaar shopping spree',
        ],
        places: [
            { slug: 'cappadocia-balloon', name: 'Cappadocia Hot-Air Balloon', category: 'Adventure', image: IMG.balloon, desc: 'Sunrise flight over fairy-chimney valleys. The single most-photographed activity on Instagram.' },
            { slug: 'hagia-sophia',       name: 'Hagia Sophia',     category: 'Heritage', image: IMG.skyline, desc: 'Byzantine cathedral turned mosque turned museum — 1,500 years of layered history under one dome.' },
            { slug: 'pamukkale',          name: 'Pamukkale Travertines', category: 'Nature', image: IMG.pamukkale, desc: 'Cascading white calcium pools — natural hot-spring terraces above the ancient ruins of Hierapolis.' },
            { slug: 'grand-bazaar',       name: 'Grand Bazaar (Istanbul)', category: 'Shopping', image: IMG.market, desc: '4,000 shops under vaulted ceilings — carpets, lanterns, evil eyes, Turkish delight.' },
            { slug: 'bosphorus-cruise',   name: 'Bosphorus Cruise', category: 'Sightseeing', image: IMG.skyline, desc: 'Boat between Europe and Asia, past Ottoman palaces and waterfront mansions.' },
        ],
    }),

    D({
        slug: 'london', kind: 'top', title: 'London',
        location: 'Westminster · Tower Bridge · Camden',
        country: 'United Kingdom',
        days: 5, nights: 4,
        image: IMG.bigben,
        gallery: [IMG.london, IMG.london2, IMG.skyline, IMG.market],
        bestTime: 'May - Sep',
        tags: ['Family', 'City', 'Heritage'],
        intro: 'Old grandeur, modern grit, fish-and-chips on rainy nights. London is best done slowly, on foot, with a tube card in your pocket.',
        highlights: [
            'Tower of London + Crown Jewels',
            'London Eye sunset capsule',
            'Buckingham Palace changing of the guard',
            'Harry Potter studio tour',
            'Camden + Notting Hill walking tour',
        ],
        places: [
            { slug: 'tower-of-london',  name: 'Tower of London',   category: 'Heritage', image: IMG.london2, desc: '900-year-old Norman fortress, home to the Crown Jewels and the famous Beefeater guards.' },
            { slug: 'london-eye',       name: 'London Eye',        category: 'Landmark', image: IMG.bigben, desc: '135m observation wheel on the Thames. Sunset capsule for the postcard view.' },
            { slug: 'buckingham-palace', name: 'Buckingham Palace', category: 'Landmark', image: IMG.london, desc: 'Catch the Changing of the Guard at 11am (alternate days). The royal residence since 1837.' },
            { slug: 'harry-potter',     name: 'Harry Potter Studio Tour', category: 'Adventure', image: IMG.market, desc: 'Warner Bros. studio in Watford — Diagon Alley sets, Hogwarts model, butterbeer.' },
            { slug: 'tower-bridge',     name: 'Tower Bridge',      category: 'Landmark', image: IMG.bigben, desc: 'Iconic Victorian draw-bridge. Walk the high-level glass floor for views down the Thames.' },
        ],
    }),

    D({
        slug: 'mauritius', kind: 'top', title: 'Mauritius',
        location: 'Indian Ocean island paradise',
        country: 'Mauritius',
        days: 6, nights: 5,
        image: IMG.catamaran,
        gallery: [IMG.chamarel, IMG.casela, IMG.blackRiver, IMG.beach],
        bestTime: 'May - Dec',
        tags: ['Honeymoon', 'Beach', 'Family'],
        intro: 'A creole-French-Indian-English island all rolled into one — Mauritius has the bluest beaches, friendliest people and best curry-rougaille on earth.',
        highlights: [
            'Ile aux Cerfs catamaran cruise',
            'Underwater seabed walk',
            'Black-river gorges national park',
            'Chamarel seven-coloured earth',
            'Casela wildlife adventure park',
        ],
        places: [
            { slug: 'ile-aux-cerfs',  name: 'Ile aux Cerfs', category: 'Beach', image: IMG.beach, desc: 'Lagoon island day-trip — speedboat over, beach lunch, snorkel and parasailing.' },
            { slug: 'chamarel',       name: 'Chamarel Seven-Coloured Earth', category: 'Nature', image: IMG.chamarel, desc: 'Surreal sand dunes in seven natural shades, plus a 100m waterfall next door.' },
            { slug: 'black-river',    name: 'Black River Gorges National Park', category: 'Nature', image: IMG.blackRiver, desc: 'Mauritius\' biggest national park — endemic kestrel, pink-pigeon trails and viewpoints.' },
            { slug: 'casela',         name: 'Casela World of Adventures', category: 'Adventure', image: IMG.casela, desc: 'Walk with lions (yes, really), zip-lines, quad biking and a giant tortoise sanctuary.' },
            { slug: 'underwater-walk', name: 'Underwater Sea Walk', category: 'Adventure', image: IMG.snorkel, desc: 'Don a Jules-Verne-style helmet and walk on the seabed feeding tropical fish.' },
        ],
    }),

    /* ============================================================
     * POPULAR HOLIDAYS — curated India-focused themed escapes (8)
     * ============================================================ */
    D({
        slug: 'kerala-honeymoon-special', kind: 'popular',
        title: 'Kerala Honeymoon Special',
        location: 'Cochin · Munnar · Thekkady · Alleppey',
        country: 'India',
        days: 6, nights: 5,
        image: IMG.backwaters,
        gallery: [IMG.teaEstate, IMG.spice, IMG.forest, IMG.beach],
        bestTime: 'Oct - Mar',
        tags: ['Honeymoon', 'Backwaters', 'Nature'],
        intro: 'Backwater houseboats, tea-soaked hills and candlelit Ayurveda dinners — Kerala writes the honeymoon playbook. Slow, green, and properly romantic.',
        highlights: [
            'Houseboat overnight on Alleppey backwaters',
            'Tea-estate sunrise walk in Munnar',
            'Spice plantation tour at Thekkady',
            'Kathakali + Kalaripayattu cultural evening',
            'Cochin fort area + Chinese fishing nets',
        ],
        places: [
            { slug: 'alleppey-houseboat', name: 'Alleppey Houseboat', category: 'Backwaters', image: IMG.backwaters, desc: 'Overnight on a kettuvallam through palm-lined canals — Karimeen fish curry as the sun sets.' },
            { slug: 'munnar-tea',         name: 'Munnar Tea Estates', category: 'Nature', image: IMG.teaEstate, desc: 'Endless emerald slopes, sunrise at Top Station, tea-museum factory tour.' },
            { slug: 'thekkady-spice',     name: 'Thekkady Spice Plantation', category: 'Nature', image: IMG.spice, desc: 'Walk through cardamom, pepper and clove gardens. Periyar tiger reserve boat ride next door.' },
            { slug: 'cochin-fort',        name: 'Fort Kochi', category: 'Heritage', image: IMG.market, desc: 'Chinese fishing nets, Dutch palaces, Jew Town spice market and St. Francis Church.' },
            { slug: 'kathakali',          name: 'Kathakali & Kalari', category: 'Culture', image: IMG.folkDance, desc: 'Watch the make-up applied live, then a 90-minute classical dance-drama performance.' },
        ],
    }),

    D({
        slug: 'goa-beach-special', kind: 'popular',
        title: 'Goa Beach Special',
        location: 'North Goa · South Goa',
        country: 'India',
        days: 5, nights: 4,
        image: IMG.goa,
        gallery: [IMG.beach, IMG.market, IMG.spice, IMG.streetfood],
        bestTime: 'Nov - Feb',
        tags: ['Beach', 'Friends', 'Family'],
        intro: 'Susegad mornings, beach-shack lunches, casino-cruise evenings — Goa stays the easy-mode getaway. Bring a paperback and a swimsuit.',
        highlights: [
            'Calangute, Baga & Anjuna beach hopping',
            'Old Goa cathedrals + Fontainhas walk',
            'Dudhsagar waterfall jeep safari',
            'Sunset cruise on the Mandovi',
            'Spice plantation lunch experience',
        ],
        places: [
            { slug: 'baga-beach',     name: 'Baga & Calangute Beach', category: 'Beach', image: IMG.goa, desc: 'North Goa\'s busiest sands — water sports, Tito\'s Lane nightlife, beach-shack feni cocktails.' },
            { slug: 'anjuna-flea',    name: 'Anjuna Flea Market',    category: 'Shopping', image: IMG.market, desc: 'Wednesday hippie-market institution since the 1970s. Bargain-hunt for silver, tie-dye and trinkets.' },
            { slug: 'old-goa',        name: 'Old Goa Churches',      category: 'Heritage', image: IMG.market, desc: 'Basilica of Bom Jesus and Sé Cathedral — Portuguese-era UNESCO sites with St. Francis Xavier\'s relics.' },
            { slug: 'dudhsagar',      name: 'Dudhsagar Waterfalls',  category: 'Nature', image: IMG.waterfall, desc: 'India\'s 5th-tallest waterfall. Jeep safari into Bhagwan Mahaveer sanctuary, then a swim.' },
            { slug: 'fontainhas',     name: 'Fontainhas Latin Quarter', category: 'Heritage', image: IMG.market, desc: 'Pastel Portuguese mansions on cobbled lanes — Panjim\'s prettiest neighbourhood.' },
        ],
    }),

    D({
        slug: 'rajasthan-royals', kind: 'popular',
        title: 'Rajasthan Royals',
        location: 'Jaipur · Jodhpur · Udaipur · Jaisalmer',
        country: 'India',
        days: 8, nights: 7,
        image: IMG.hawaMahal,
        gallery: [IMG.amerFort, IMG.udaipur, IMG.jaisalmer, IMG.camel],
        bestTime: 'Oct - Mar',
        tags: ['Heritage', 'Culture', 'Family'],
        intro: 'Pink, blue and white cities in one trip. Forts, royal palaces, camel rides under desert stars — Rajasthan never gets old.',
        highlights: [
            'Amber Fort jeep ride in Jaipur',
            'Mehrangarh Fort sunset in Jodhpur',
            'Lake Pichola boat ride in Udaipur',
            'Camel safari + desert camp in Jaisalmer',
            'Rajasthani folk-dance dinner experience',
        ],
        places: [
            { slug: 'amber-fort',     name: 'Amber Fort (Jaipur)', category: 'Heritage', image: IMG.amerFort, desc: 'Hilltop honey-stone fortress. Jeep ride up, mirror-tiled Sheesh Mahal at the top.' },
            { slug: 'hawa-mahal',     name: 'Hawa Mahal (Jaipur)', category: 'Heritage', image: IMG.hawaMahal, desc: '953-window pink-sandstone "Palace of Winds" — the most-photographed facade in Rajasthan.' },
            { slug: 'mehrangarh',     name: 'Mehrangarh Fort (Jodhpur)', category: 'Heritage', image: IMG.fort, desc: '125m sandstone fort towering over the blue city. Sunset views are otherworldly.' },
            { slug: 'lake-pichola',   name: 'Lake Pichola (Udaipur)', category: 'Sightseeing', image: IMG.udaipur, desc: 'Boat ride past the floating Lake Palace and the Jag Mandir. India\'s most romantic city.' },
            { slug: 'thar-desert',    name: 'Thar Desert Camel Safari (Jaisalmer)', category: 'Adventure', image: IMG.camel, desc: 'Sam Sand Dunes camel ride at sunset, then folk-music dinner under the stars at a desert camp.' },
        ],
    }),

    D({
        slug: 'kashmir-paradise', kind: 'popular',
        title: 'Kashmir Paradise',
        location: 'Srinagar · Gulmarg · Pahalgam',
        country: 'India',
        days: 6, nights: 5,
        image: IMG.shikara,
        gallery: [IMG.snowSlope, IMG.mountain, IMG.tulip, IMG.mughal],
        bestTime: 'Apr - Oct',
        tags: ['Honeymoon', 'Nature', 'Mountain'],
        intro: 'Snow-capped mountains, mirror-still lakes and Kashmiri wazwan dinners on a houseboat. The "paradise on earth" cliché is fully earned.',
        highlights: [
            'Shikara ride on Dal Lake',
            'Gulmarg gondola — phase 1 + 2',
            'Pahalgam Aru valley horse-ride',
            'Tulip garden (Mar - Apr only)',
            'Mughal gardens + Shankaracharya temple',
        ],
        places: [
            { slug: 'dal-lake',         name: 'Dal Lake & Shikara Ride', category: 'Sightseeing', image: IMG.shikara, desc: 'Sunrise shikara ride past floating gardens, lotus blooms and shoulder-to-shoulder houseboats.' },
            { slug: 'gulmarg-gondola',  name: 'Gulmarg Gondola', category: 'Adventure', image: IMG.snowSlope, desc: 'World\'s second-highest cable car. Phase 1 to Kongdoori, Phase 2 to Apharwat (4,000m).' },
            { slug: 'pahalgam-aru',     name: 'Aru Valley (Pahalgam)', category: 'Nature', image: IMG.mountain, desc: 'Pine-forested meadows, the Lidder river, horse-rides up to Lidderwat. Pahalgam at its prettiest.' },
            { slug: 'tulip-garden',     name: 'Indira Gandhi Tulip Garden', category: 'Nature', image: IMG.tulip, desc: 'Asia\'s largest tulip garden — 1.5 million bulbs in 70+ varieties (Mar-Apr only).' },
            { slug: 'mughal-gardens',   name: 'Mughal Gardens', category: 'Heritage', image: IMG.mughal, desc: 'Shalimar Bagh, Nishat Bagh and Chashme Shahi — Persian-style terraced gardens by Shah Jahan.' },
        ],
    }),

    D({
        slug: 'himachal-heaven', kind: 'popular',
        title: 'Himachal Heaven',
        location: 'Shimla · Manali · Solang',
        country: 'India',
        days: 6, nights: 5,
        image: IMG.toyTrain,
        gallery: [IMG.snow, IMG.rohtang, IMG.mountain, IMG.market],
        bestTime: 'Mar - Jun, Oct - Feb',
        tags: ['Hill Station', 'Adventure', 'Family'],
        intro: 'Pine forests, Beas-river roadside dhabas, snow-laden Solang slopes. Himachal does mountain getaways effortlessly — ideal for first-time hill goers.',
        highlights: [
            'Toy-train ride to Shimla',
            'Solang Valley adventure sports',
            'Rohtang Pass snowpoint (subject to weather)',
            'Hidimba Devi temple + Old Manali walk',
            'Mall-road shopping & cafe-hopping',
        ],
        places: [
            { slug: 'shimla-toy-train', name: 'Kalka–Shimla Toy Train', category: 'Sightseeing', image: IMG.toyTrain, desc: 'UNESCO heritage railway. 5 hours, 102 tunnels, 800 bridges through the lower Himalayas.' },
            { slug: 'solang-valley',    name: 'Solang Valley', category: 'Adventure', image: IMG.snowSlope, desc: 'Manali\'s adventure playground — paragliding, zorbing, snow-skiing in winter, ATV rides in summer.' },
            { slug: 'rohtang-pass',     name: 'Rohtang Pass', category: 'Adventure', image: IMG.rohtang, desc: '3,978m pass with year-round snow patches. Permit required, but the views are unforgettable.' },
            { slug: 'hidimba-temple',   name: 'Hidimba Devi Temple', category: 'Heritage', image: IMG.temple, desc: '500-year-old wooden pagoda temple in a deodar forest. Old Manali at its mystical best.' },
            { slug: 'mall-road',        name: 'Shimla Mall Road', category: 'Shopping', image: IMG.market, desc: 'British-era promenade — Christ Church, the Ridge, Scandal Point and old-school cafes.' },
        ],
    }),

    D({
        slug: 'andaman-islands', kind: 'popular',
        title: 'Andaman Islands',
        location: 'Port Blair · Havelock · Neil',
        country: 'India',
        days: 6, nights: 5,
        image: IMG.radhanagar,
        gallery: [IMG.scuba, IMG.cellular, IMG.beach, IMG.snorkel],
        bestTime: 'Oct - May',
        tags: ['Beach', 'Honeymoon', 'Adventure'],
        intro: 'India\'s best-kept tropical secret. White-sand beaches, world-class diving, and a hint of cellular-jail history — the Andamans are unreal.',
        highlights: [
            'Radhanagar beach (Asia\'s best) at sunset',
            'Scuba diving off Havelock reefs',
            'Neil island bicycle exploration',
            'Cellular Jail light-and-sound show',
            'Glass-bottom boat coral viewing',
        ],
        places: [
            { slug: 'radhanagar-beach', name: 'Radhanagar Beach', category: 'Beach', image: IMG.radhanagar, desc: 'TIME magazine voted this Asia\'s best beach. Powder-fine sand, walk-out shallow turquoise.' },
            { slug: 'havelock-scuba',   name: 'Havelock Scuba & Snorkel', category: 'Adventure', image: IMG.scuba, desc: 'Some of Asia\'s clearest reef diving — manta rays, parrotfish, even occasional dugongs.' },
            { slug: 'cellular-jail',    name: 'Cellular Jail', category: 'Heritage', image: IMG.cellular, desc: 'Port Blair\'s "Kala Pani" colonial prison. Sobering tour by day, light-and-sound show by night.' },
            { slug: 'neil-island',      name: 'Neil Island Cycling', category: 'Adventure', image: IMG.beach, desc: 'Tiny island where everyone gets around by bicycle. Bharatpur, Sitapur and Laxmanpur beaches.' },
            { slug: 'glass-boat',       name: 'Glass-Bottom Boat Ride', category: 'Adventure', image: IMG.snorkel, desc: 'North Bay\'s coral reef without getting wet. Great for kids and non-swimmers.' },
        ],
    }),

    D({
        slug: 'north-east-tribal-trail', kind: 'popular',
        title: 'North-East Tribal Trail',
        location: 'Guwahati · Kaziranga · Shillong · Cherrapunji',
        country: 'India',
        days: 7, nights: 6,
        image: IMG.rhino,
        gallery: [IMG.rootBridge, IMG.shillong, IMG.waterfall, IMG.forest],
        bestTime: 'Oct - Apr',
        tags: ['Nature', 'Adventure', 'Culture'],
        intro: 'Off-the-tourist-trail, raw and ridiculously green. Tea estates, tribal hospitality, root-bridges and rhinos — the North-East is India\'s last frontier.',
        highlights: [
            'One-horned rhino safari at Kaziranga',
            'Living-root bridge trek at Cherrapunji',
            'Shillong viewpoint + Don Bosco museum',
            'Umiam Lake boating',
            'Mawlynnong "cleanest village in Asia" walk',
        ],
        places: [
            { slug: 'kaziranga-rhino',  name: 'Kaziranga Rhino Safari', category: 'Adventure', image: IMG.rhino, desc: 'UNESCO national park — two-thirds of the world\'s one-horned rhinos. Jeep + elephant safari.' },
            { slug: 'living-root-bridges', name: 'Living-Root Bridges', category: 'Nature', image: IMG.rootBridge, desc: 'Cherrapunji\'s Khasi-tribe wonders — bridges woven from living rubber-tree roots over decades.' },
            { slug: 'shillong-viewpoint', name: 'Shillong Peak & Don Bosco Museum', category: 'Sightseeing', image: IMG.shillong, desc: 'Highest viewpoint in Meghalaya plus the world\'s 2nd-largest tribal-culture museum.' },
            { slug: 'mawlynnong',       name: 'Mawlynnong "Cleanest Village"', category: 'Sightseeing', image: IMG.forest, desc: 'Voted Asia\'s cleanest village — bamboo skywalk, women-led cooperative, riverside lunch.' },
            { slug: 'cherrapunji-falls', name: 'Nohkalikai Falls', category: 'Nature', image: IMG.waterfall, desc: 'India\'s tallest plunge waterfall — 340m drop into a turquoise pool below.' },
        ],
    }),

    D({
        slug: 'tamil-nadu-temple-trail', kind: 'popular',
        title: 'Tamil Nadu Temple Trail',
        location: 'Chennai · Mahabalipuram · Tanjore · Madurai · Rameswaram',
        country: 'India',
        days: 7, nights: 6,
        image: IMG.tanjore,
        gallery: [IMG.madurai, IMG.rameswaram, IMG.chettinad, IMG.fort],
        bestTime: 'Nov - Mar',
        tags: ['Heritage', 'Culture', 'Family'],
        intro: 'Towering gopurams, Chola-era bronzes, filter coffee and pongal mornings. Tamil Nadu is the deep-south spiritual circuit done premium.',
        highlights: [
            'Brihadeeshwara temple at Tanjore (UNESCO)',
            'Meenakshi temple complex at Madurai',
            'Shore temple + Pancha Rathas at Mahabalipuram',
            'Rameswaram Ramanathaswamy + Dhanushkodi',
            'Filter-coffee + Chettinad cuisine experiences',
        ],
        places: [
            { slug: 'brihadeeshwara',   name: 'Brihadeeshwara Temple (Tanjore)', category: 'Temple', image: IMG.tanjore, desc: '1,000-year-old Chola wonder. Tallest temple of its time, all granite, all UNESCO.' },
            { slug: 'meenakshi-temple', name: 'Meenakshi Temple (Madurai)', category: 'Temple', image: IMG.madurai, desc: '14 gopurams, 33,000 sculptures. The most ornate temple complex in the south.' },
            { slug: 'mahabalipuram',    name: 'Mahabalipuram Shore Temple', category: 'Heritage', image: IMG.fort, desc: '7th-century Pallava sea-shore temple. Pancha Rathas and Krishna\'s Butterball nearby.' },
            { slug: 'rameswaram',       name: 'Ramanathaswamy Temple (Rameswaram)', category: 'Temple', image: IMG.rameswaram, desc: 'One of the four Char Dham. Longest temple corridor in India (1,200m).' },
            { slug: 'chettinad-cuisine', name: 'Chettinad Mansions & Cuisine', category: 'Food', image: IMG.chettinad, desc: 'Mansion-stay heritage tour, plus the famous Chettinad pepper-chicken and karuvepilai-podi.' },
        ],
    }),
];
